language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - '4.0'
  - '4.1'
  - '5.0'
sudo: false
before_install:
  - brew install mpg123
install:
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=a5609b81800d154cfe00648f8ffeb68b76ce273637c6bee3d89e818bac6d6452 codeclimate-test-reporter < coverage/lcov.info
